---
- name: installing tomcat
  hosts: all
  become: yes
  tasks:
    - name: update ubuntu
      ansible.builtin.apt:
        update_cache: yes
        state: present
    - name: install java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present
    - name: adding user tomcat
      ansible.builtin.user:
        name: tomcat
        shell: /bin/home
        group: tomcat
    - name: create tomcat directory
      ansible.builtin.file:
        path: /opt/tomcat
        state: directory
        mode: 755
    - name: Unarchive a file that needs to be downloaded
      ansible.builtin.unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.80/bin/apache-tomcat-9.0.80.tar.gz
        dest: /opt/tomcat
        remote_src: yes
    - name: change ownership of tomcat 
      ansible.builtin.file:
        name: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: 0755
        recurse: yes
    - name: Start and Enable Tomcat on sever
      ansible.builtin.service:
        name: tomcat9
        state: started
        daemon_reload: true
    - name: deploy war file
      ansible.builtin.get_url:
        url: https://github.com/NeerajaaG/netflix-444.git
        dest: /var/lib/tomcat9/webapps/
